metabase:
   container_name: metabase
   image: metabase/metabase:latest
   ports:
     - "3000:3000"
   environment:
      - DB_HOST: $HOST
      - DB_PORT: $PORT  # Replace with your RDS port
      - DB_USER: $USER
      - DB_PASSWORD: $PASSWORD
      - DB_NAME: $DBNAME